// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfButton uIItem1Button = this.UIWPFCalculatorWindow.UIItem1Button;
            WpfButton uIItemButton2 = this.UIWPFCalculatorWindow.UIItemButton2;
            WpfButton uIItemButton4 = this.UIWPFCalculatorWindow.UIItemButton4;
            WpfButton uIItemButton1 = this.UIWPFCalculatorWindow.UIItemButton1;
            WpfButton uIItem3Button = this.UIWPFCalculatorWindow.UIItem3Button;
            WpfButton uIItemButton = this.UIWPFCalculatorWindow.UIItemButton;
            WpfButton uIItem6Button = this.UIWPFCalculatorWindow.UIItem6Button;
            WpfButton uIItemButton3 = this.UIWPFCalculatorWindow.UIItemButton3;
            WpfButton uIItem0Button = this.UIWPFCalculatorWindow.UIItem0Button;
            WinButton uIOKButton = this.UIWPFCalculatorWindow1.UIOKWindow.UIOKButton;
            WpfButton uIItem9Button = this.UIWPFCalculatorWindow.UIItem9Button;
            WpfButton uIItem8Button = this.UIWPFCalculatorWindow.UIItem8Button;
            WpfButton uISqrtButton = this.UIWPFCalculatorWindow.UISqrtButton;
            WpfButton uIItem5Button = this.UIWPFCalculatorWindow.UIItem5Button;
            WpfButton uIItemButton6 = this.UIWPFCalculatorWindow.UIItemButton6;
            WpfButton uIItem4Button = this.UIWPFCalculatorWindow.UIItem4Button;
            WpfButton uIMButton = this.UIWPFCalculatorWindow.UIMButton;
            WpfButton uIItemButton5 = this.UIWPFCalculatorWindow.UIItemButton5;
            WpfButton uIMRButton = this.UIWPFCalculatorWindow.UIMRButton;
            WpfButton uICButton = this.UIWPFCalculatorWindow.UICButton;
            WpfButton uIMCButton = this.UIWPFCalculatorWindow.UIMCButton;
            #endregion

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(21, 33));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(25, 30));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(40, 39));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(36, 31));

            // Click '-' button
            Mouse.Click(uIItemButton1, new Point(29, 33));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(42, 29));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(26, 30));

            // Click '*' button
            Mouse.Click(uIItemButton, new Point(33, 38));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(43, 31));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(32, 36));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(35, 25));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(42, 22));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(41, 32));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(36, 13));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(40, 22));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(40, 25));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(38, 41));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(24, 35));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(39, 27));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(30, 36));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(38, 38));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(35, 31));

            // Click 'Sqrt' button
            Mouse.Click(uISqrtButton, new Point(37, 33));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(20, 35));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(47, 34));

            // Click '%' button
            Mouse.Click(uIItemButton6, new Point(26, 36));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(37, 28));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(43, 33));

            // Click 'Sqrt' button
            Mouse.Click(uISqrtButton, new Point(31, 33));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(46, 35));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(43, 33));

            // Click '%' button
            Mouse.Click(uIItemButton6, new Point(38, 19));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(32, 34));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(28, 24));

            // Click '%' button
            Mouse.Click(uIItemButton6, new Point(30, 27));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(42, 34));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(35, 31));

            // Click '*' button
            Mouse.Click(uIItemButton, new Point(36, 34));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(31, 38));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(27, 30));

            // Click 'M+' button
            Mouse.Click(uIMButton, new Point(42, 29));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(35, 44));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(37, 31));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(24, 26));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(40, 28));

            // Click '+/-' button
            Mouse.Click(uIItemButton5, new Point(40, 31));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(30, 31));

            // Click '*' button
            Mouse.Click(uIItemButton, new Point(33, 43));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(37, 38));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(33, 39));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(33, 29));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(31, 30));

            // Click 'MR' button
            Mouse.Click(uIMRButton, new Point(44, 30));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(25, 31));

            // Click 'C' button
            Mouse.Click(uICButton, new Point(24, 30));

            // Click 'MC' button
            Mouse.Click(uIMCButton, new Point(33, 27));
        }
        
        #region Properties
        public UIWPFCalculatorWindow UIWPFCalculatorWindow
        {
            get
            {
                if ((this.mUIWPFCalculatorWindow == null))
                {
                    this.mUIWPFCalculatorWindow = new UIWPFCalculatorWindow();
                }
                return this.mUIWPFCalculatorWindow;
            }
        }
        
        public UIWPFCalculatorWindow1 UIWPFCalculatorWindow1
        {
            get
            {
                if ((this.mUIWPFCalculatorWindow1 == null))
                {
                    this.mUIWPFCalculatorWindow1 = new UIWPFCalculatorWindow1();
                }
                return this.mUIWPFCalculatorWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIWPFCalculatorWindow mUIWPFCalculatorWindow;
        
        private UIWPFCalculatorWindow1 mUIWPFCalculatorWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWPFCalculatorWindow : WpfWindow
    {
        
        public UIWPFCalculatorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "WPF Calculator";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("WPF Calculator");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B1";
                    this.mUIItem1Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B2";
                    this.mUIItem2Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B3";
                    this.mUIItem3Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BMultiply";
                    this.mUIItemButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem6Button
        {
            get
            {
                if ((this.mUIItem6Button == null))
                {
                    this.mUIItem6Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem6Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B6";
                    this.mUIItem6Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem6Button;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B5";
                    this.mUIItem5Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BMinus";
                    this.mUIItemButton1.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B9";
                    this.mUIItem9Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BPlus";
                    this.mUIItemButton2.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B4";
                    this.mUIItem4Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BDevide";
                    this.mUIItemButton3.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem8Button
        {
            get
            {
                if ((this.mUIItem8Button == null))
                {
                    this.mUIItem8Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem8Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B8";
                    this.mUIItem8Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem8Button;
            }
        }
        
        public WpfButton UIItem1XButton
        {
            get
            {
                if ((this.mUIItem1XButton == null))
                {
                    this.mUIItem1XButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1XButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BOneOver";
                    this.mUIItem1XButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem1XButton;
            }
        }
        
        public WpfButton UISqrtButton
        {
            get
            {
                if ((this.mUISqrtButton == null))
                {
                    this.mUISqrtButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISqrtButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BSqrt";
                    this.mUISqrtButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUISqrtButton;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BEqual";
                    this.mUIItemButton4.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfButton UIMButton
        {
            get
            {
                if ((this.mUIMButton == null))
                {
                    this.mUIMButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BMemPlus";
                    this.mUIMButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIMButton;
            }
        }
        
        public WpfButton UIItemButton5
        {
            get
            {
                if ((this.mUIItemButton5 == null))
                {
                    this.mUIItemButton5 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton5.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BPM";
                    this.mUIItemButton5.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton5;
            }
        }
        
        public WpfButton UIItemButton6
        {
            get
            {
                if ((this.mUIItemButton6 == null))
                {
                    this.mUIItemButton6 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton6.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BPercent";
                    this.mUIItemButton6.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItemButton6;
            }
        }
        
        public WpfButton UIMRButton
        {
            get
            {
                if ((this.mUIMRButton == null))
                {
                    this.mUIMRButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMRButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BMemRecall";
                    this.mUIMRButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIMRButton;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "B0";
                    this.mUIItem0Button.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UICButton
        {
            get
            {
                if ((this.mUICButton == null))
                {
                    this.mUICButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BC";
                    this.mUICButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUICButton;
            }
        }
        
        public WpfButton UIMCButton
        {
            get
            {
                if ((this.mUIMCButton == null))
                {
                    this.mUIMCButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMCButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "BMemClear";
                    this.mUIMCButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIMCButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem6Button;
        
        private WpfButton mUIItem5Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem8Button;
        
        private WpfButton mUIItem1XButton;
        
        private WpfButton mUISqrtButton;
        
        private WpfButton mUIItemButton4;
        
        private WpfButton mUIMButton;
        
        private WpfButton mUIItemButton5;
        
        private WpfButton mUIItemButton6;
        
        private WpfButton mUIMRButton;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUICButton;
        
        private WpfButton mUIMCButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWPFCalculatorWindow1 : WinWindow
    {
        
        public UIWPFCalculatorWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "WPF Calculator";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("WPF Calculator");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("WPF Calculator");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("WPF Calculator");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
